language: android

dist: xenial

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - build-tools-27.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

jdk:
  - openjdk12

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libstdc++6

script:
  - ./gradlew check
