name: Release and Deploy

on:
  push:
    branches:
      - stable
      - '[0-9]+.[0-9]+'

jobs:
  test-linux:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      env:
        EXCLUDE_ANDROID: false
        EXCLUDE_KTOR: false
        EXCLUDE_TFX: false
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
        BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
      run: ./gradlew check bintrayUpload
  test-win:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      env:
        EXCLUDE_ANDROID: false
        EXCLUDE_KTOR: false
        EXCLUDE_TFX: false
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
        BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
      run: ./gradlew check bintrayUpload
  test-macOS:
    runs-on: [macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      env:
        EXCLUDE_ANDROID: true
        EXCLUDE_KTOR: true
        EXCLUDE_TFX: true
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
        BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        RUN_ID: ${{ github.event.id }} 
      run: ./gradlew check -x jsTest bintrayUpload
